export const timezones = [
  { value: "Africa/Abidjan", label: "Abidjan (Africa/Abidjan)" },
  { value: "Africa/Accra", label: "Accra (Africa/Accra)" },
  { value: "Australia/Adelaide", label: "Adelaide (Australia/Adelaide)" },
  { value: "Africa/Addis_Ababa", label: "Addis Ababa (Africa/Addis_Ababa)" },
  { value: "Africa/Algiers", label: "Algiers (Africa/Algiers)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (Europe/Amsterdam)" },
  { value: "America/Anchorage", label: "Anchorage (America/Anchorage)" },
  { value: "Europe/Athens", label: "Athens (Europe/Athens)" },
  { value: "Pacific/Auckland", label: "Auckland (Pacific/Auckland)" },
  { value: "Asia/Baghdad", label: "Baghdad (Asia/Baghdad)" },
  { value: "Asia/Baku", label: "Baku (Asia/Baku)" },
  { value: "Asia/Bangkok", label: "Bangkok (Asia/Bangkok)" },
  { value: "Asia/Beirut", label: "Beirut (Asia/Beirut)" },
  { value: "Europe/Belgrade", label: "Belgrade (Europe/Belgrade)" },
  { value: "Europe/Berlin", label: "Berlin (Europe/Berlin)" },
  { value: "America/Bogota", label: "Bogota (America/Bogota)" },
  { value: "Australia/Brisbane", label: "Brisbane (Australia/Brisbane)" },
  { value: "Europe/Brussels", label: "Brussels (Europe/Brussels)" },
  { value: "Europe/Bucharest", label: "Bucharest (Europe/Bucharest)" },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires (America/Argentina/Buenos_Aires)" },
  { value: "Europe/Budapest", label: "Budapest (Europe/Budapest)" },
  { value: "Africa/Cairo", label: "Cairo (Africa/Cairo)" },
  { value: "America/Caracas", label: "Caracas (America/Caracas)" },
  { value: "Africa/Casablanca", label: "Casablanca (Africa/Casablanca)" },
  { value: "America/Chicago", label: "Chicago - Central Time (America/Chicago)" },
  { value: "Asia/Colombo", label: "Colombo (Asia/Colombo)" },
  { value: "Europe/Copenhagen", label: "Copenhagen (Europe/Copenhagen)" },
  { value: "Asia/Damascus", label: "Damascus (Asia/Damascus)" },
  { value: "Australia/Darwin", label: "Darwin (Australia/Darwin)" },
  { value: "America/Denver", label: "Denver - Mountain Time (America/Denver)" },
  { value: "Asia/Dhaka", label: "Dhaka (Asia/Dhaka)" },
  { value: "Europe/Dublin", label: "Dublin (Europe/Dublin)" },
  { value: "Asia/Dubai", label: "Dubai (Asia/Dubai)" },
  { value: "Pacific/Fiji", label: "Fiji (Pacific/Fiji)" },
  { value: "Pacific/Guam", label: "Guam (Pacific/Guam)" },
  { value: "America/Guatemala", label: "Guatemala (America/Guatemala)" },
  { value: "Europe/Helsinki", label: "Helsinki (Europe/Helsinki)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (Asia/Hong_Kong)" },
  { value: "Pacific/Honolulu", label: "Honolulu (Pacific/Honolulu)" },
  { value: "Europe/Istanbul", label: "Istanbul (Europe/Istanbul)" },
  { value: "Asia/Jakarta", label: "Jakarta (Asia/Jakarta)" },
  { value: "Asia/Jerusalem", label: "Jerusalem (Asia/Jerusalem)" },
  { value: "Africa/Johannesburg", label: "Johannesburg (Africa/Johannesburg)" },
  { value: "Asia/Karachi", label: "Karachi (Asia/Karachi)" },
  { value: "Asia/Kathmandu", label: "Kathmandu (Asia/Kathmandu)" },
  { value: "Asia/Kolkata", label: "Kolkata - India (Asia/Kolkata)" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur (Asia/Kuala_Lumpur)" },
  { value: "Asia/Kuwait", label: "Kuwait (Asia/Kuwait)" },
  { value: "Europe/Kiev", label: "Kyiv (Europe/Kiev)" },
  { value: "Africa/Lagos", label: "Lagos (Africa/Lagos)" },
  { value: "America/Lima", label: "Lima (America/Lima)" },
  { value: "Europe/Lisbon", label: "Lisbon (Europe/Lisbon)" },
  { value: "Europe/London", label: "London (Europe/London)" },
  { value: "America/Los_Angeles", label: "Los Angeles - Pacific Time (America/Los_Angeles)" },
  { value: "Europe/Madrid", label: "Madrid (Europe/Madrid)" },
  { value: "Asia/Manila", label: "Manila (Asia/Manila)" },
  { value: "Australia/Melbourne", label: "Melbourne (Australia/Melbourne)" },
  { value: "America/Mexico_City", label: "Mexico City (America/Mexico_City)" },
  { value: "America/Montevideo", label: "Montevideo (America/Montevideo)" },
  { value: "Europe/Moscow", label: "Moscow (Europe/Moscow)" },
  { value: "Africa/Nairobi", label: "Nairobi (Africa/Nairobi)" },
  { value: "America/New_York", label: "New York - Eastern Time (America/New_York)" },
  { value: "Europe/Oslo", label: "Oslo (Europe/Oslo)" },
  { value: "Pacific/Pago_Pago", label: "Pago Pago (Pacific/Pago_Pago)" },
  { value: "Europe/Paris", label: "Paris (Europe/Paris)" },
  { value: "Australia/Perth", label: "Perth (Australia/Perth)" },
  { value: "America/Phoenix", label: "Phoenix - MST (America/Phoenix)" },
  { value: "Pacific/Port_Moresby", label: "Port Moresby (Pacific/Port_Moresby)" },
  { value: "Europe/Prague", label: "Prague (Europe/Prague)" },
  { value: "Asia/Riyadh", label: "Riyadh (Asia/Riyadh)" },
  { value: "Europe/Rome", label: "Rome (Europe/Rome)" },
  { value: "America/Santiago", label: "Santiago (America/Santiago)" },
  { value: "America/Sao_Paulo", label: "São Paulo (America/Sao_Paulo)" },
  { value: "Asia/Seoul", label: "Seoul (Asia/Seoul)" },
  { value: "Asia/Shanghai", label: "Shanghai (Asia/Shanghai)" },
  { value: "Asia/Singapore", label: "Singapore (Asia/Singapore)" },
  { value: "Europe/Sofia", label: "Sofia (Europe/Sofia)" },
  { value: "Europe/Stockholm", label: "Stockholm (Europe/Stockholm)" },
  { value: "Australia/Sydney", label: "Sydney (Australia/Sydney)" },
  { value: "Asia/Taipei", label: "Taipei (Asia/Taipei)" },
  { value: "Asia/Tehran", label: "Tehran (Asia/Tehran)" },
  { value: "Asia/Tokyo", label: "Tokyo (Asia/Tokyo)" },
  { value: "Pacific/Tongatapu", label: "Tongatapu (Pacific/Tongatapu)" },
  { value: "America/Toronto", label: "Toronto (America/Toronto)" },
  { value: "Africa/Tunis", label: "Tunis (Africa/Tunis)" },
  { value: "UTC", label: "UTC - Coordinated Universal Time (UTC)" },
  { value: "America/Vancouver", label: "Vancouver (America/Vancouver)" },
  { value: "Europe/Vienna", label: "Vienna (Europe/Vienna)" },
  { value: "Europe/Warsaw", label: "Warsaw (Europe/Warsaw)" },
  { value: "Europe/Zurich", label: "Zurich (Europe/Zurich)" }
];
