import { db } from "$lib/server/db/database";
import * as schema from "$lib/server/db/schema";
import { hashPassword } from "$lib/utils/password";
import { json, type RequestHandler } from "@sveltejs/kit";

export const POST: RequestHandler = async ({ request }) => {
  try {
    let body;
    try {
      body = await request.json();
    } catch (e) {
      return json(
        { success: false, error: "Invalid JSON in request body" },
        { status: 400 }
      );
    }

    const { user } = body as { user?: { name?: string; email?: string; password?: string } };

    // Validation
    if (!user) {
      return json(
        { success: false, error: "User object is required" },
        { status: 400 }
      );
    }

    if (!user.name || !user.email || !user.password) {
      return json(
        {
          success: false,
          error: "Missing required fields: name, email, and password are required"
        },
        { status: 400 }
      );
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(user.email)) {
      return json(
        { success: false, error: "Invalid email format" },
        { status: 400 }
      );
    }

    if (user.name.trim().length === 0) {
      return json(
        { success: false, error: "Name cannot be empty" },
        { status: 400 }
      );
    }

    if (user.password.length < 8) {
      return json(
        { success: false, error: "Password must be at least 8 characters" },
        { status: 400 }
      );
    }

    // Create user (ID is auto-generated by PostgreSQL)
    const [createdUser] = await db.insert(schema.user).values({
      email: user.email,
      name: user.name,
      emailVerified: true,
      role: "admin",
      banned: false,
      notificationPreferences: {
        dashboard: {
          ticketCreated: true,
          itemAssigned: true,
          itemUpdated: true,
          itemClosed: true
        },
        email: {
          ticketCreated: true,
          itemAssigned: true,
          itemUpdated: true,
          itemClosed: true
        }
      }
    }).returning();


    // Create credential account linked to the user
    await db.insert(schema.account).values({
      accountId: createdUser.id.toString(), // Use user ID as accountId for credentials
      providerId: "credential",
      userId: createdUser.id,
      password: await hashPassword(user.password),
    });

    return json({
      success: true,
    });

  } catch (error: any) {
    console.error("Error creating user:", error);

    // Handle PostgreSQL unique constraint violation (duplicate email)
    if (error.code === "23505" || error.constraint?.includes("email")) {
      return json(
        { success: false, error: "Email already exists" },
        { status: 409 }
      );
    }

    // Handle foreign key constraint violation
    if (error.code === "23503") {
      return json(
        { success: false, error: "Database constraint violation" },
        { status: 400 }
      );
    }

    // Handle check constraint violation
    if (error.code === "23514") {
      return json(
        { success: false, error: "Database constraint violation" },
        { status: 400 }
      );
    }

    // Handle not-null constraint violation
    if (error.code === "23502") {
      return json(
        { success: false, error: "Missing required database field" },
        { status: 400 }
      );
    }

    // Handle connection errors
    if (error.code === "ECONNREFUSED" || error.code === "ETIMEDOUT") {
      return json(
        { success: false, error: "Database connection failed" },
        { status: 503 }
      );
    }

    // Generic error
    return json(
      { success: false, error: "Failed to create user" },
      { status: 500 }
    );
  }
};
