import { db } from '$lib/server/db/database';
import * as schema from '$lib/server/db/schema';
import { ValidationError } from '$lib/server/errors';
import { hashPassword } from '$lib/utils/password';
import { json, type RequestHandler } from '@sveltejs/kit';

export const POST: RequestHandler = async ({ request }) => {
  const { user } = await request.json() as { user: { name: string; email: string; password: string } };

  if (!user)
    throw new ValidationError('User object is required');

  if (!user.name || !user.email || !user.password)
    throw new ValidationError('Missing required fields: name, email, and password are required');

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  if (!emailRegex.test(user.email))
    throw new ValidationError('Invalid email format');

  if (user.name.trim().length === 0)
    throw new ValidationError('Name cannot be empty');


  if (user.password.length < 8)
    throw new ValidationError('Password must be at least 8 characters');

  // Create user (ID is auto-generated by PostgreSQL)
  const [createdUser] = await db.insert(schema.user).values({
    email: user.email,
    name: user.name,
    emailVerified: true,
    role: 'admin',
    banned: false,
    notificationPreferences: {
      dashboard: {
        ticketCreated: true,
        itemAssigned: true,
        itemUpdated: true,
        itemClosed: true
      },
      email: {
        ticketCreated: true,
        itemAssigned: true,
        itemUpdated: true,
        itemClosed: true
      }
    }
  }).returning();


  // Create credential account linked to the user
  await db.insert(schema.account).values({
    accountId: createdUser.id.toString(),
    providerId: 'credential',
    userId: createdUser.id,
    password: await hashPassword(user.password),
  });

  return json({
    success: true,
  });
};
